extend = "env.toml"

[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
# a list of crate members. since we do not have a Cargo.toml, we will need to specify this in here.
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = [
    "kernel",
    "qemu-common",
	"runner",
	"userspace"
]

[env.gdb]
GDB_LISTEN=true

[tasks.run]
workspace = false
description = "Run the kernel"
dependencies = [{name = "run", path = "kernel/"}]

[tasks.bin]
workspace = false
dependencies = [{name = "bin", path = "userspace/"}]

