[build]
target = ["x86_64-unknown-none"]
rustflags = [
	"-C", "relocation-model=static",
	"-C", "link-arg=-T../exec_linker.ld",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-no-pie",
	"-C", "force-unwind-tables=yes",
]

