extend = "../env.toml"

[env]
CARGO_MAKE_WORKSPACE_EMULATION = false

[tasks.copy-bin]
condition = { files_modified = { input = ["../userspace/bin/*"], output = ["./src/progs/*"]}}
dependencies = [{name = "bin", path = "../userspace"}]
script_runner = "@duckscript"
#"glob_cp ../userspace/bin/* ./src/progs"
script = '''
arr = glob_array ../userspace/bin/*
for bin in ${arr}
	name = basename ${bin}
	echo cp ${bin} ./src/progs/${name}
	cp ${bin} ./src/progs/${name}
end
'''
# args = ["../userspace/bin/*", "./src/progs/"]

[tasks.build-base]
command = "cargo"
args = ["build", "@@split(CARGO_BUILD_ARGS,;)"]
toolchain = "nightly"
dependencies = ["copy-bin"]

[tasks.build]
dependencies = ["build-base", { name = "build", path = "../runner" }]
command = "../runner/target/release/runner${EXECUTABLE_EXTENSION}"
args = ["--target", "target/", "--build", "target/x86_64-unknown-none/${CARGO_BUILD_DEST}/blog_os_kernel"]


[tasks.run]
extend = "build-base"
args = ["run"]
dependencies = ["copy-bin", { name = "build", path = "../runner" }]

[tasks.test-lib]
extend = "run"
args = ["test", "--lib"]

[tasks.test-bin]
extend = "run"
args = ["test", "--bin", "blog_os_kernel"]


[tasks.test]
dependencies = ["test-bin", "test-lib"]


[tasks.docs]
command = "cargo"
args = ["doc"]
toolchain = "nightly"
