[env]
CARGO_MAKE_WORKSPACE_EMULATION = false

[tasks.build]
description = "Build the runner executable"
command = "cargo"
args = ["build", "--release"]
toolchain = "nightly"

[tasks.docs]
command = "cargo"
args = ["doc"]
toolchain = "nightly"