[env]
CARGO_MAKE_WORKSPACE_EMULATION = false

[tasks.build]
condition = { files_modified = { input = ["./src/**/*.rs"], output = ["./target/release/*"]}}
description = "Build the runner executable"
command = "cargo"
args = ["build", "--release"]
toolchain = "nightly"

[tasks.docs]
command = "cargo"
args = ["doc"]
toolchain = "nightly"